In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("train.txt",sep=";",header=None,names=["Text","Emotions"])

In [3]:
df.head()

                                                Text Emotions
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
df.isnull().sum()

Text        0
Emotions    0
dtype: int64

In [5]:
df=df.drop_duplicates()

In [6]:
unique_emotion=df["Emotions"].unique()

In [7]:
unique_emotion

<StringArray>
['sadness', 'anger', 'love', 'surprise', 'fear', 'joy']
Length: 6, dtype: str

In [8]:
# Mapping Target Value into Numbers
unique={}
i=0
for emo in unique_emotion:
        unique[emo]=i
        i+=1
df["Emotions"]=df["Emotions"].map(unique).astype(int)
df

                                                    Text  Emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[15999 rows x 2 columns]

# Text Processing

<h3>Convert to Lowercase</h3>

In [9]:
def toLowerCase(text:str):
        return text.lower()
df["Text"]=df["Text"].apply(toLowerCase)

# Remove URLs

In [10]:
import re

def remove_urls(text: str) -> str:
    pattern = r'https?://\S+|www\.\S+'
    return re.sub(pattern, '', text)

df["Text"]=df["Text"].apply(remove_urls)

# Remove Digits

In [11]:
def remove_digits(text: str):
    return re.sub(r'\d+', '', text)

df["Text"]=df["Text"].apply(remove_digits)

# Remove Emojies

In [12]:

def remove_emojis(text: str) -> str:
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F" 
        "\U0001F300-\U0001F5FF" 
        "\U0001F680-\U0001F6FF" 
        "\U0001F1E0-\U0001F1FF" 
        "\U00002700-\U000027BF" 
        "\U0001F900-\U0001F9FF" 
        "\U00002600-\U000026FF"
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub('', text)

df["Text"]=df["Text"].apply(remove_emojis)

# Remove Punctuations

In [13]:
import string

def remove_punctuation(text: str) -> str:
    return text.translate(str.maketrans('', '', string.punctuation))

df["Text"]=df["Text"].apply(remove_punctuation)

In [36]:
import nltk
# nltk.download('punkt_tab')
# nltk.download('stopwords')
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
stop_words = set(stopwords.words("english"))

In [35]:
def remove_stop_word(text:str)->str:
        tokens_word=word_tokenize(text)
        filtered_word=[
                word for word in tokens_word
                if word.lower() not in stop_words
        ]
        return " ".join(filtered_word)

remove_stop_word('i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake')

'go feeling hopeless damned hopeful around someone cares awake'

<h3>Remove Stop words because they don't effect in NLP</h3>

In [38]:
df["cleaned_text"]=df["Text"].apply(remove_stop_word)
df.tail()

,Text,Emotions,cleaned_text
15995,i just had a very brief time in the beanbag an...,0,brief time beanbag said anna feel like beaten
15996,i am now turning and i feel pathetic that i am...,0,turning feel pathetic still waiting tables sub...
15997,i feel strong and good overall,5,feel strong good overall
15998,i feel like this was such a rude comment and i...,1,feel like rude comment im glad
15999,i know a lot but i feel so stupid because i ca...,0,know lot feel stupid portray